config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'books/index'

  root 'books#index'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  dragonfly_accessor :image do
    default Rails.root.join('public', 'images', 'default', 'default.png')

  end
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new

  end

  def create
    @book = current_user.books.build(book_params)
    @book.save
    redirect_to books_path
  end

  def show
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book

    else
      render 'edit'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :content, :category_novel, :category_fantasy,
                                 :category_historical, :category_biography, :image, :draft)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/registrations_controller_helper.rb
module RegistrationsControllerHelper
end

app/views/books/_form.html.erb
<div class="show">
  <div class="card">


    <%= form_for @book do |f| %>
        <div class="other_put_field">
          <br/>
          <p></p>
          <br/>
          <table>
            <tr>
              <td>
                Название:
              </td>
              <td>
                <%= f.text_area :title, size: '45' %>
              </td>
            </tr>
            <tr>
              <td>
                Автор:
              </td>
              <td>
                <%= f.text_area :author, size: '45' %>
              </td>
            </tr>

            <tr>
              <td>
                Обложка:
              </td>
              <td>
                <%= f.file_field :image %>
              </td>
            </tr>
            <tr>
              <td>
                Жанры:
              </td>
              <td>
                <%= f.check_box :category_historical, {}, 'true', 'false' %>
                <%= 'Исторический' %><br/>
                <%= f.check_box :category_novel, {}, 'true', 'false' %>
                <%= 'Роман' %><br/>
                <%= f.check_box :category_biography, {}, 'true', 'false' %>
                <%= 'Биография' %><br/>
                <%= f.check_box :category_fantasy, {}, 'true', 'false' %>
                <%= 'Фантастика' %><br/>
              </td>
            </tr>
            <tr>
              <td>Дополнительно:</td>
              <td>
                <%= f.check_box :draft, {}, 'true', 'false' %>
                <%= 'Черновик' %>
              </td>
            </tr>

          </table>
        </div>
        <div class="content_field">
          <p align="center">Содержание:</p>
          <%= f.text_area :content, size: "100x10" %>
        </div>
        <div class="submit" align="center">
          <%= f.submit value='Cохранить', class: 'c' %>
        </div>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<div class="main">
  <% @books.each do |book| %>
      <% if !book.draft %>
          <div class="book">

            <div class="image">
              <div>
                <%= image_tag book.image.url, height: 200 %>
              </div>

            </div>

            <table>
              <tr>
                <td> Автор:</td>
                <td><%= book.author %></td>
              </tr>

              <tr>
                <td>Название:</td>
                <td><%= book.title %></td>
              </tr>
              <tr>
                <td>Жанры:</td>
                <td>
                  <% if book.category_novel %>
                      <%= 'Роман' %><br/>
                  <% end %>
                  <% if book.category_fantasy %>
                      <%= 'Фантастика' %><br/>
                  <% end %>
                  <% if book.category_historical %>
                      <%= 'Историческая' %><br/>
                  <% end %>
                  <% if book.category_biography %>
                      <%= 'Биография' %><br/>
                  <% end %>
                </td>
              </tr>


            </table>
            <div class="buttons">

              <table>
                <tr>
                  <%= link_to 'Просмотр', book_path(book), class: 'c' %>
                </tr>


                <% if user_signed_in? && current_user.id == book.user_id %>
                    <tr><%= link_to 'Изменить', edit_book_path(book), class: 'c' %></tr>
                    <tr>
                      <%= link_to 'Удалить', book_path(book), method: :delete, data: {confirm: 'are you sure?'}, class: 'c' %>
                    </tr>
                <% end %>

              </table>

            </div>

          </div>
      <% else %>
          <% if user_signed_in? && current_user.id == book.user_id %>
              <div class="book">

                <div class="image">
                  <div>
                    <%= image_tag book.image.url, height: 200 %>
                    <%= 'Черновик'%>
                  </div>

                </div>

                <table>
                  <tr>
                    <td> Автор:</td>
                    <td><%= book.author %></td>
                  </tr>

                  <tr>
                    <td>Название:</td>
                    <td><%= book.title %></td>
                  </tr>


                  <tr>
                    <td>Жанры:</td>
                    <td>
                      <% if book.category_novel %>
                          <%= 'Роман' %><br/>
                      <% end %>
                      <% if book.category_fantasy %>
                          <%= 'Фантастика' %><br/>
                      <% end %>
                      <% if book.category_historical %>
                          <%= 'Историческая' %><br/>
                      <% end %>
                      <% if book.category_biography %>
                          <%= 'Биография' %><br/>
                      <% end %>
                    </td>
                  </tr>

                </table>

                <div class="buttons">

                  <table>
                    <tr>
                      <%= link_to 'Просмотр', book_path(book), class: 'c' %>
                    </tr>


                    <% if user_signed_in? && current_user.id == book.user_id %>
                        <tr><%= link_to 'Изменить', edit_book_path(book), class: 'c' %></tr>
                        <tr>
                          <%= link_to 'Удалить', book_path(book), method: :delete, data: {confirm: 'are you sure?'}, class: 'c' %>
                        </tr>
                    <% end %>

                  </table>

                </div>

              </div>
          <% end %>
      <% end %>


  <% end %>
</div>

app/views/books/new.html.erb
<%= render 'form'%>

app/views/books/show.html.erb
<div class="show" align="center">
  <div class="card">
    <div>
      <div class="text">
        <table class="title">
          <tr>
            <td>Автор:</td>
            <td><%= @book.author %></td>
          </tr>
          <tr>
            <td>Название:</td>
            <td><%= @book.title %></td>
          </tr>
          <tr>
            <td>Жанры:</td>
            <td>
              <% if @book.category_novel %>
                  <%= 'Роман' %><br/>
              <% end %>
              <% if @book.category_fantasy %>
                  <%= 'Фантастика' %><br/>
              <% end %>
              <% if @book.category_historical %>
                  <%= 'Историческая' %><br/>
              <% end %>
              <% if @book.category_biography %>
                  <%= 'Биография' %><br/>
              <% end %>
            </td>
          </tr>
          <% if @book.draft %>
              <tr>
                <td>Черновик</td>
              </tr>
              <tr>
          <% end %>
          <td></td>
          <td align="right">

            <% if user_signed_in? && current_user.id == @book.user_id %>
                <div><%= link_to 'Изменить', edit_book_path(@book), class: 'c' %></div>
                <div><%= link_to 'Удалить', book_path(@book), method: :delete, class: 'c' %></div>
            <% end %>
          </td>
          </tr>
        </table>
      </div>
      <div class="image">
        <%= image_tag @book.image.url, height: 300 %>
      </div>
      <div style="clear: right;"></div>
    </div>

    <div class="content">
      <h3 align="center">Краткое содержание</h3>
      <%= @book.content %>
    </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SlobodaTask</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
<div>

  <div class="r">
    <% if user_signed_in? %>
        <span class="content"><%= current_user.email %></span>
        <%= link_to 'Выйти', destroy_user_session_path, :method => :delete, class: 'c' %>
    <% else %>
        <%= link_to 'Войти', new_user_session_path, class: 'c' %>
        или <%= link_to 'Зарегистрироваться', new_user_registration_path, class: 'c' %>
    <% end %>
    <%= link_to 'На главную', books_path, class: 'c' %>
    <%= link_to 'Добавить книгу', new_book_path, class: 'c' %>
  </div>
</div>
<%= yield %>
</body>
</html>